### ISSUE TITLE
执行了 bell-db 下的sql文件, 部分数据表没数据.

### ISSUE THREAD

**Issue by songyinjun2008** [jwgl/bell-tm-core#69]
ea_view.sql 里 ea.dv_menu 创建失败
menu表没有name/label_cn等字段
create or replace view ea.dv_menu as
with recursive r as (
    select m.id, m.name, m.label_cn, m.label_en,
    from ea.menu m

ea/tm 下的system_user 表没有数据, 该如何登录?

**Comment by todoubaba** [comment]
1、ea现在没有可执行项目，所以不需要menu。
2、如果有ZF系统，同步获取数据；否则，自己创建数据。

**Comment by songyinjun2008** [comment]
ZF库,是正方教务管理系统的数据库... 看来得自己建数据了. 多谢.
