### ISSUE TITLE
如何启动前端项目

### ISSUE THREAD

**Issue by songyinjun2008** [jwgl/bell-tm-core#70]
tm-core-web 项目已经移除
有两个前端项目 bell-tm-client 和 bell-tm-static 
下载安装的方式安装了nodejs 版本 node-v9.3.0-linux-x64
bell-tm-static 执行 npm start 命令成功, 应该如何访问? url是什么?
bell-tm-client 
执行命令安装 ng 
npm install -g @angular/cli

执行 ng serve时报错
先执行了 npm i --save-dev @angular-devkit/build-angular 解决第一个报错
又执行了 npm install node-sass --save-dev 去解决 "Cannot find module 'node-sass'"时, 这个命令执行过程中报错, node-sass无法安装.
应该用哪个版本的nodejs?

**Comment by songyinjun2008** [comment]
解决了, 换了最新版的nodejs. 
执行 npm install @angular-devkit/build-angular --unsafe-perm
执行 npm start

**Comment by todoubaba** [comment]
1、nodejs 10.x。
2、使用ng build --watch构造tm-bell-client。
3、使用nginx做前端server。配置为：```
    server {
        server_name tm.local;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forworded-For $proxy_add_x_forwarded_for;

        location = /login {
            proxy_pass http://localhost:8080;
        }

        location = /logout {
            proxy_pass http://localhost:8080;
        }

        location /uaa/ {
            proxy_pass http://localhost:9999;
        }

        location ~ /api/(menus) {
            rewrite /api/(.*) /$1 break;
            proxy_pass http://localhost:8080;
        }
       
        location /api/ {
            proxy_pass http://localhost:8080;
        }

        location / {
            root  #path to bell-tm-client/dist/bell-tm-client;

            if ($http_x_requested_with = XMLHttpRequest) {
                return 200;
            }

            try_files $uri $uri/ /index.html;
        }
```
